services:
  db:
    image: postgres:16-alpine
    container_name: money-manager-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: money_manager_2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        DATABASE_URL: "postgresql://postgres:postgres@db:5432/money_manager_2?schema=public"
    container_name: money_manager-api
    depends_on:
      - db
    environment:
      # Port für NestJS (wie in main.ts/ConfigService)
      API_PORT: 4000
      # Hostname ist der Sevice-Name 'db', nicht localhost

      DATABASE_URL: "postgresql://postgres:postgres@db:5432/money_manager_2?schema=public"
      NODE_ENV: production
    ports:
      - "4000:4000"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: money_manager-web
    depends_on:
      - api
    environment:
      NODE_ENV: production
      # Später nice: NEXT_PUBLIC_API_URL: "http://localhost:4000"
    ports:
      - "3000:3000"

volumes:
  db_data:
